package PgDataApp;
use Moose;
use namespace::autoclean;

use RapidApp 1.3001;

use Catalyst qw/
    -Debug
    RapidApp::TabGui
    RapidApp::RapidDbic
    RapidApp::NavCore
    RapidApp::CoreSchemaAdmin
/;

extends 'Catalyst';

our $VERSION = '0.01';

__PACKAGE__->config(
    name => 'PgDataApp',

    # The general 'RapidApp' config controls aspects of the special components that
    # are globally injected/mounted into the Catalyst application dispatcher:
    'RapidApp' => {
      ## To change the root RapidApp module to be mounted someplace other than
      ## at the root (/) of the Catalyst app (default is '' which is the root)
      #module_root_namespace => 'adm',

      ## To load additional, custom RapidApp modules (under the root module):
      #load_modules => { somemodule => 'Some::RapidApp::Module::Class' },

      ## To set a custom favicon for all pages generated by RapidApp
      #default_favicon_url => '/assets/rapidapp/misc/static/images/rapidapp_icon_small.ico',
    },
		
		'Plugin::RapidApp::TabGui' => {
		  dashboard_url => '/tple/site/dashboard.md',
		},
		
	  'Controller::RapidApp::Template' => {
	    # Templates ending in *.html can be accessed without the extension:
	    default_template_extension => 'html',
			access_class => 'PgDataApp::Template::Access',
	  }

);

# Start the application
__PACKAGE__->setup();

1;


# ---
# This app was initially generated/bootrapped with:
#  rapidapp.pl --helpers RapidDbic PgDataApp -- --blank-ddl
# ---


__END__

=head1 NAME

PgDataApp - Catalyst/RapidApp based application

=head1 SYNOPSIS

    script/pgdataapp_server.pl

=head1 DESCRIPTION

[enter your description here]

=head1 SEE ALSO

L<RapidApp>, L<Catalyst>

=head1 AUTHOR

Henry Van Styn

=head1 LICENSE

This library is free software. You can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
